### ISSUE TITLE
Transition not firing on image load.

### ISSUE THREAD

**Issue by RobertBroersma** [tjoskar/ng-lazyload-image#228]
Hi there.

I'm a bit stumped. I've got the following code:

CSS:
```
[lazyLoad] {
	opacity: 0;
	transition: opacity .4s;
}

.ng-lazyloaded {
	opacity: 1;
}
```

And HTML:
```
<img lazyLoad="../imgs/sport.jpg" alt="Sports">
```

But the transition doesn't seem to fire when the image is loaded. Frankly I'm out of ideas as to what the issue could be, so I'm hoping this is a common issue and someone knows a solution.

I've checked: removing other classes from the image. Making sure there's not other influences on the opacity of the img. No other transitions. It does transition when I switch `.ng-lazyloaded` on and off in the debugger.

**Comment by tjoskar** [comment]
Hi,

Attribute selection and class selection has the same priority. Meaning, it depends on what order you are declaring the css rules. https://jsbin.com/xofovuqiti/edit?html,css,output

Can you try to add `!important` to `ng-lazyloaded`:
```css
[lazyLoad] {
  opacity: 0;
  transition: opacity .4s;
}

.ng-lazyloaded {
  opacity: 1 !important;
}
```

Or using the `ng-lazyloading` class which will be removed when the image is loaded.

```css
img {
  transition: opacity .4s;
}

.ng-lazyloading {
  opacity: 0;
}

.ng-lazyloaded {
  opacity: 1;
}
```

```html
<img lazyLoad="../imgs/sport.jpg" class="ng-lazyloading" alt="Sports">
```
