### ISSUE TITLE
How to create a transition effect between defaultImage and lazyLoad

### ISSUE THREAD

**Issue by AndreasSchmid1** [tjoskar/ng-lazyload-image#300]
Hello tjoskar. Thank you for this great library! I want to ask if it is possible to create a transition effect beween the defaultImage and the lazy loaded image.

Thank you for help in advance

**Comment by tjoskar** [comment]
HI @AndreasSchmid1, thanks for your kind words. 

You can add an animation on the image, eg.
```css
img.ng-lazyloaded {
  animation: fadein .5s;
}
@keyframes fadein {
  from { opacity: 0; }
  to   { opacity: 1; }
}
```
(see "Default image" on the example page: https://tjoskar.github.io/ng-lazyload-image)

You can also add a transition between images if you create two images, one with the default image and one with the lazyloaded one. eg. https://github.com/tjoskar/ng-lazyload-image/blob/master/example/pixelated-image.component.ts (see "Pixelated image" on the example page: https://tjoskar.github.io/ng-lazyload-image)
As you may know, you can slow down the animation to get a better look at the animation (https://developers.google.com/web/tools/chrome-devtools/inspect-styles/animations).

It is also possible to add a transition on the `background-image`:
```css
img {
  height: 250px;
  width: 500px;
  transition: background-image 1s ease-out;
}
```
```html
<div [defaultImage]="defaultImage" [lazyLoad]="image"></div>
```

See this page for an example (not using ng-lazyload-image): http://jsfiddle.net/8L7775fa/4/

Let me know if you run into problems.
