### ISSUE TITLE
Create a `netlify.toml` file

### ISSUE THREAD

**Issue by tjoskar** [tjoskar/ng-lazyload-image#419]
The demo page is hosted on netlify with the default config that doesn't support SPA. Create a `netlify.toml` file in the root folder with the following content:
```toml
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
```
